apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flink-taskmanager-hpa
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flink-taskmanager
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  - type: Pods
    pods:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30